name: balance

services:
  database:
    image: gvenzl/oracle-xe:21-slim
    container_name: balance-db
    platform: linux/amd64
    environment:
      - ORACLE_PASSWORD=admin123
      - ORACLE_DATABASE=BALANCE
      - APP_USER=balance
      - APP_USER_PASSWORD=balance
    ports:
      - "1521:1521"
    volumes:
      - dbdata:/opt/oracle/oradata
    networks:
      - balance-net
    
    
volumes:
  dbdata:

networks:
  balance-net: