name: balance

services:
  database:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: balance-db
    platform: linux/amd64
    environment:
      - ORACLE_PWD=admin123
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - dbdata:/opt/oracle/oradata
      - ./scripts:/opt/oracle/scripts/startup
    networks:
      - balance-net
    
    
volumes:
  dbdata:

networks:
  balance-net: